import os, string, re, shutil
import glob
from pathlib import Path

configfile: "config/config.json"

### Config Variables
### ----------------------------------------------------------------------------

DataFolder = config['DataFolder']
fastx_extension = config["extension"]

# Samples
files = os.listdir(DataFolder)
complete_extensions = [config["mates"]["mate1"] + config['extension'],
                       config["mates"]["mate2"] + config['extension']]
replacement = '|'.join(complete_extensions)

samples = set([re.sub(replacement, "", file) for file in files])

mates = list(config['mates'].values())
#------------------------------------------------------------------------------

## Pipeline with pooling of reads
#------------------------------------------------------------------------------

rule all:
    input: #"results/5_report/pipeline_finished.txt"
 #     expand("results/5_report/{sample}_report.html", sample =samples),
      expand("results/{sample}/report/pipeline_finished.txt", \
             sample = samples)

include: "rules/QC.smk"
include: "rules/spades.smk"
include: "rules/quast.smk"
include: "rules/busco.smk"
include: "rules/confindr.smk"
include: "rules/prokka.smk"
include: "rules/generate_report_individual.smk"
include: "rules/finish.smk"
